### ISSUE TITLE
一点改进建议

### ISSUE THREAD

**Issue by snikeguo** [YRG1009/GD32MCUInfoQuery#1]
1.买一个VPS，写好GD32数据库服务器代码，技术栈推荐.net core+任意一款RPC框架，如Xrpc,数据库采用sqlite3
2.申请一个域名指向你的IP
2.用户这边推荐使用WPF框架，打开软件后，自动连接域名+端口，更新数据，用户每次查询数据，都通过RPC传到服务器，服务器这边返回查询结果。通过MVVM模式更新到UI界面。
完毕

**Comment by Jack1009HF** [comment]
非常感谢您的建议！
我们会认真考虑并评估实现的可能性，为用户提供更好的使用体验。
后期也有可能直接提供网页版本，通过网页进行查询。
祝好！

**Comment by Jack1009HF** [comment]
> 1.买一个VPS，写好GD32数据库服务器代码，技术栈推荐.net core+任意一款RPC框架，如Xrpc,数据库采用sqlite3
> 2.申请一个域名指向你的IP
> 2.用户这边推荐使用WPF框架，打开软件后，自动连接域名+端口，更新数据，用户每次查询数据，都通过RPC传到服务器，服务器这边返回查询结果。通过MVVM模式更新到UI界面。
> 完毕

非常感谢您的建议！
我们会认真考虑并评估实现的可能性，为用户提供更好的使用体验。
后期也有可能直接提供网页版本，通过网页进行查询。
祝好！

**Comment by snikeguo** [comment]
网页非常不错
